In [175]:
import numpy as np

## 1.14

In [246]:
X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
X_exp = np.exp(X)

expSum = np.sum(X_exp, axis = 1)
expSum = expSum.reshape(-1,1)

X_exp / expSum

array([[0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096]])

## 1.15

In [24]:
x = np.array([6,4,8,7,5,3,2,9,1])
k = 3

def kWinsorowksaMean(x, k):
    
    x.sort()
    replaceFirstK = x[k]
    replaceLastK = x[-k-1]
    spliced = x[k:-k]

    return np.r_[np.repeat(replaceFirstK, k), spliced, np.repeat(replaceLastK, k)].mean()

kWinsorowksaMean(x,k)

[4 4 4 4 5 6 6 6 6]


5.0

## 1.16

In [16]:
def stirling(n):
    return np.power((n/np.e),n)*np.sqrt(2*np.pi*n)
stirling(5)

118.0191679575901

## 1.17

In [39]:
def leibniz(n):
    indexes = np.arange(n)
    oddEven = [(1 if el%2 else -1) for el in indexes]
    return -np.sum(oddEven/(2*indexes + 1))*4
    
print(leibniz(100000))
print(np.pi)

3.141582653589792
3.141592653589793


## 1.19

In [127]:
x = np.array([1,2,np.NaN,3,np.NaN])
def substituteNaN(x):
    notNan = x[~np.isnan(x)]
    notNan.mean()
    x[np.isnan(x)] = notNan.mean()
    return x
substituteNaN(x)

array([1., 2., 2., 3., 2.])

## 1.20

In [149]:
result = np.array([])
for i in np.arange(12):
    if  str(np.pi)[i] == '.':
        continue
    result = np.r_[result,int(str(np.pi)[i])]
result

array([3., 1., 4., 1., 5., 9., 2., 6., 5., 3., 5.])

## 1.21

In [165]:
x = np.array([6,4,8,7,5,3,2,9,1,9,9,6,5,5,5,5])

unq = (np.unique(x, return_counts = True))
unq[0][unq[1].argmax()]

5

## 1.22

In [169]:
def regression(x,y):
    beta = np.sum((x-x.mean())*(y - y.mean()))/np.sum((x-x.mean())**2)
    alfa = y.mean() - beta*x.mean()
    return [alfa,beta]

x = np.array([1,2,3])
y = np.array([2,3,4])

regression(x,y)

[1.0, 1.0]

## 1.23

In [207]:
X = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
np.flip(X,0)

array([[5, 5, 5],
       [4, 4, 4],
       [3, 3, 3],
       [2, 2, 2],
       [1, 1, 1]])

## 1.24

In [210]:
X = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
np.flip(X,1)

array([[3, 2, 1],
       [3, 2, 1],
       [3, 2, 1],
       [3, 2, 1],
       [3, 2, 1]])

## 1.25

In [255]:
X = np.array([[1,4,7],
              [2,5,8],
              [3,6,9]])


(X.min(0),X.max(0))


(array([1, 4, 7]), array([3, 6, 9]))

## 1.26

In [365]:
X = np.array([[1,1],[2,2],[3,3],[0,0]])
Y = np.array([[0.5,0.5], [2.6,2.6], [0.22,0.35]])

results = [np.argmin(np.sum((Y-row)**2, axis = 1)) for row in X]
results


[0, 1, 1, 2]

## 1.27

In [367]:
T = np.array([1,0,3,0,2])
A = np.zeros((T.size, np.max(T)+1))
A[np.arange(T.size), T] = 1
A

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

## 1.28

In [456]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [457]:
def initCentroids(points,k):
    centroids = points.copy()
    np.random.shuffle(centroids)
    return centroids[:k]

In [458]:
def closestCentroid(points,centroids):
    distances = np.sqrt((points - centroids[:,np.newaxis])**2).sum(axis=2)
    return np.argmin(distances, axis = 0)

In [468]:
def move_centroids(points, closest, centroids):
    return np.array([points[closest == k].mean(axis = 0) for k in range(centroids.shape[0])])

In [482]:
points = np.vstack(
    (
        ( (np.random.randn(150,2) * 0.75) + np.array([1,0])      ),
        ( (np.random.randn(50,2) * 0.25) + np.array([-0.5,0.5])  ),
        ( (np.random.randn(50,2) * 0.5) + np.array([-0.5,-0.5])  )

    )
);

In [497]:
# from JSAnimation import IPython_display
# from matplotlib import animation

# # create a simple animation
# fig = plt.figure()
# ax = plt.axes(xlim=(-4, 4), ylim=(-4, 4))
# centroids = initCentroids(points, 3)

# def init():
#     return

# def animate(i):
#     global centroids
#     closest = closestCentroid(points, centroids)
#     centroids = move_centroids(points, closest, centroids)
#     ax.cla()
#     ax.scatter(points[:, 0], points[:, 1], c=closest)
#     ax.scatter(centroids[:, 0], centroids[:, 1], c='r', s=100)
#     return 

# animation.FuncAnimation(fig, animate, init_func=init,
#                         frames=10, interval=200, blit=True)

## 1.29

In [505]:
grades = np.array(((0,0.01,0.1,0.2), (0.01, 0.05,0.03,0.1),(0.1,0.03, 0.05,0.01),(0.2,0.1,0.01,0)))
columnSums = grades.sum(1)
rowSums = grades.sum(0)

np.outer(columnSums,rowSums)

array([[0.0961, 0.0589, 0.0589, 0.0961],
       [0.0589, 0.0361, 0.0361, 0.0589],
       [0.0589, 0.0361, 0.0361, 0.0589],
       [0.0961, 0.0589, 0.0589, 0.0961]])