In [139]:
import numpy as np

## 1.15

In [24]:
x = np.array([6,4,8,7,5,3,2,9,1])
k = 3

def kWinsorowksaMean(x, k):
    
    x.sort()
    replaceFirstK = x[k]
    replaceLastK = x[-k-1]
    spliced = x[k:-k]

    return np.r_[np.repeat(replaceFirstK, k), spliced, np.repeat(replaceLastK, k)].mean()

kWinsorowksaMean(x,k)

[4 4 4 4 5 6 6 6 6]


5.0

## 1.16

In [16]:
def stirling(n):
    return np.power((n/np.e),n)*np.sqrt(2*np.pi*n)
stirling(5)

118.0191679575901

## 1.17

In [39]:
def leibniz(n):
    indexes = np.arange(n)
    oddEven = [(1 if el%2 else -1) for el in indexes]
    return -np.sum(oddEven/(2*indexes + 1))*4
    
print(leibniz(100000))
print(np.pi)

3.141582653589792
3.141592653589793


## 1.19

In [127]:
x = np.array([1,2,np.NaN,3,np.NaN])
def substituteNaN(x):
    notNan = x[~np.isnan(x)]
    notNan.mean()
    x[np.isnan(x)] = notNan.mean()
    return x
substituteNaN(x)

array([1., 2., 2., 3., 2.])

## 1.20

In [149]:
result = np.array([])
for i in np.arange(12):
    if  str(np.pi)[i] == '.':
        continue
    result = np.r_[result,int(str(np.pi)[i])]
result

array([3., 1., 4., 1., 5., 9., 2., 6., 5., 3., 5.])

## 1.21

In [165]:
x = np.array([6,4,8,7,5,3,2,9,1,9,9,6,5,5,5,5])

unq = (np.unique(x, return_counts = True))
unq[0][unq[1].argmax()]

5