In [1]:
import numpy as np

## Tworzenie, kształty, podstawy

In [2]:
x = np.array([1,4,3,2,5,6])
x

array([1, 4, 3, 2, 5, 6])

In [3]:
x.ndim

1

In [4]:
x.shape

(6,)

In [5]:
x.size

6

In [6]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
A.ndim, A.shape, A.size

(2, (3, 3), 9)

In [8]:
x.shape = (2,3)

In [9]:
x

array([[1, 4, 3],
       [2, 5, 6]])

In [10]:
x.ndim, x.shape, x.size

(2, (2, 3), 6)

In [14]:
B = A.reshape(1,9)
B

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
x.reshape(-1,6)

array([[1, 4, 3, 2, 5, 6]])

In [16]:
x.reshape(6,-1)

array([[1],
       [4],
       [3],
       [2],
       [5],
       [6]])

In [18]:
A.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
A.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Typy danych

In [21]:
A.dtype

dtype('int64')

In [22]:
x.astype(np.str_)

array([['1', '4', '3'],
       ['2', '5', '6']], 
      dtype='<U21')

In [24]:
np.array([1, 1.23, True, "asd"])

array(['1', '1.23', 'True', 'asd'], 
      dtype='<U32')

In [25]:
np.array([1, 1.23, True])

array([ 1.  ,  1.23,  1.  ])

## Tworzenie wektorów o ustalonej strukturze

In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [28]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [29]:
np.eye(5) # jak I w matematyce, czyli macierz jednostkowa

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [30]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [31]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [33]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [34]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

## Losowanie

In [35]:
np.random.uniform(-4,4,10)

array([ 0.0723066 ,  2.30993404, -1.71655999,  0.17795037, -0.71150565,
        0.43388559, -2.96855861,  3.11761333, -0.93782268, -3.43468447])

In [37]:
np.random.uniform(-4,4,(2,3))

array([[-2.00707991,  0.97892263,  2.9729467 ],
       [-1.38503185,  1.37014546, -0.36436652]])

In [36]:
np.random.normal(-4,0.1,10)

array([-3.92652674, -4.01424374, -4.00258645, -3.98583815, -3.90565764,
       -4.07224494, -3.95698432, -4.08882638, -4.00498749, -3.88371031])

In [38]:
np.random.normal(-4,0.1,(3,2))

array([[-3.95034482, -3.83311224],
       [-4.0931889 , -4.059685  ],
       [-4.10091247, -4.00236671]])

In [40]:
np.random.randint(2,5,(2,4))

array([[4, 3, 2, 4],
       [4, 2, 4, 2]])

In [41]:
np.random.choice([10,100,1000,10000, 100000], 3, replace=False)

array([    10, 100000,  10000])

In [42]:
np.random.choice([10,100,1000,10000, 100000], 3, replace=True)

array([1000, 1000,  100])

In [43]:
np.random.choice(["Maciek", "Kasia", "Zosia"], 3, replace=True)

array(['Maciek', 'Zosia', 'Maciek'], 
      dtype='<U6')

## Powtórzenia

In [44]:
np.repeat(5,6)

array([5, 5, 5, 5, 5, 5])

In [45]:
np.repeat([1,2],6)

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])

In [46]:
np.repeat([1,2],[2,3])

array([1, 1, 2, 2, 2])

In [47]:
np.tile(5,6)

array([5, 5, 5, 5, 5, 5])

In [48]:
np.tile([1,2],6)

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [49]:
np.tile([1,2],[2,3])

array([[1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2]])

## Wstawianie wiersza/kolumny

In [50]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np.vstack((A, [100,99,98]))

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100,  99,  98]])

In [53]:
np.hstack((A, [[100],[99],[98]]))

array([[  1,   2,   3, 100],
       [  4,   5,   6,  99],
       [  7,   8,   9,  98]])

In [54]:
np.insert(A, 2, [100,99,97], axis=1)

array([[  1,   2, 100,   3],
       [  4,   5,  99,   6],
       [  7,   8,  97,   9]])

In [55]:
np.insert(A, 2, [100,99,97], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [100,  99,  97],
       [  7,   8,   9]])

## r_

In [56]:
np.r_[1:6]

array([1, 2, 3, 4, 5])

In [57]:
np.r_[1:6:2]

array([1, 3, 5])

In [59]:
np.r_[1:6:2,88,55:66:3]

array([ 1,  3,  5, 88, 55, 58, 61, 64])

In [62]:
np.r_[1:6:3j]

array([ 1. ,  3.5,  6. ])

In [65]:
np.r_[1:6:3j, 88, 99, 55:66:3]

array([  1. ,   3.5,   6. ,  88. ,  99. ,  55. ,  58. ,  61. ,  64. ])

In [66]:
np.c_[1:6:3j, [7,8,9]]

array([[ 1. ,  7. ],
       [ 3.5,  8. ],
       [ 6. ,  9. ]])

In [67]:
np.c_[1:6:3j, [7,8,9,10]]

ValueError: all the input array dimensions except for the concatenation axis must match exactly

## Wektoryzacja

In [68]:
np.array([1,2,4])+np.array([1,2,4])

array([2, 4, 8])

In [69]:
np.array([1,2,4])+np.array([1,2,4,5,6,7])

ValueError: operands could not be broadcast together with shapes (3,) (6,) 

In [72]:
A = np.arange(12).reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
np.r_[1,10,100]

array([  1,  10, 100])

In [75]:
A.shape, np.r_[1,10,100].shape

((4, 3), (3,))

In [73]:
A * np.r_[1,10,100]

array([[   0,   10,  200],
       [   3,   40,  500],
       [   6,   70,  800],
       [   9,  100, 1100]])

In [77]:
setki = np.c_[1,10,100,1000]
setki

array([[   1,   10,  100, 1000]])

In [78]:
setki.shape

(1, 4)

In [79]:
A * setki

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

In [80]:
setki = setki.reshape(A.shape[0], -1)
setki

array([[   1],
       [  10],
       [ 100],
       [1000]])

In [81]:
setki.shape

(4, 1)

In [82]:
A * setki

array([[    0,     1,     2],
       [   30,    40,    50],
       [  600,   700,   800],
       [ 9000, 10000, 11000]])

In [84]:
np.r_[1,10,100,1000].shape

(4,)

In [83]:
A * np.r_[1,10,100,1000]

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [85]:
np.array([True, False]) * np.array([2,3])

array([2, 0])

In [86]:
x = np.r_[1,4,6]
y = np.r_[3,3,7]
np.minimum(x,y)

array([1, 3, 6])

In [87]:
np.maximum(x,y)

array([3, 4, 7])

## Wektory logiczne, warunki na wektorach

In [88]:
x <= y

array([ True, False,  True], dtype=bool)

In [89]:
1 != np.eye(4)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]], dtype=bool)

In [91]:
x > 2

array([False,  True,  True], dtype=bool)

In [92]:
x < 5

array([ True,  True, False], dtype=bool)

In [90]:
(x > 2) & (x < 5) # biora wektory i zwracaja tez wektor

array([False,  True, False], dtype=bool)

In [95]:
(x > 2) | (x < 5)

array([ True,  True,  True], dtype=bool)

In [96]:
np.all((x > 2) & (x < 5))

False

In [97]:
np.all((x > 2) | (x < 5))

True

In [98]:
np.any((x > 2) & (x < 5))

True

In [99]:
np.sum(np.array([1,2,3]))

6

In [101]:
(x > 2) & (x < 5)

array([False,  True, False], dtype=bool)

In [100]:
np.sum((x > 2) & (x < 5))

1

In [103]:
np.sin([0,np.pi/2,4])

array([ 0.       ,  1.       , -0.7568025])

In [104]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [105]:
A.mean()

5.5

In [108]:
A.mean(axis=0) #ten wymiar, czyli wiersze, nam sie zapada "collapse", czyli już go nie ma

array([ 4.5,  5.5,  6.5])

In [107]:
A.mean(axis=1)

array([  1.,   4.,   7.,  10.])

## Wartości NaN

In [110]:
nanwek = np.array([1, np.NaN, 3])
nanwek

array([  1.,  nan,   3.])

In [111]:
np.sum(nanwek)

nan

In [112]:
np.nansum(nanwek)

4.0

In [113]:
np.isnan(nanwek)

array([False,  True, False], dtype=bool)

In [114]:
np.sort(nanwek)

array([  1.,   3.,  nan])